/*
 * User and Authentication Backend
 *
 * # API for authentication and managing user accounts  This is the API of the service at P7M that manages tenants, accounts and authentication. It is the basis of many services of P7M.  For most endpoints, the caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. If your interacting with this API using the Swagger interface, you need to set the JWT token by clicking on the **Authorize** button on the right side of the header. As the value don't forget that the Authorization header starts with the fixed value `Bearer` followed by a space followed by the actual JWT token value.  If anything is unclear or you found a bug in the documentation, please contact <tech@p7m.de>. 
 *
 * The version of the OpenAPI document: 0.11.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "realname")]
    pub realname: String,
    #[serde(rename = "userType")]
    pub user_type: UserType,
    #[serde(rename = "phone")]
    pub phone: String,
}

impl Account {
    pub fn new(account_id: String, tenant_id: String, username: String, password: String, realname: String, user_type: UserType, phone: String) -> Account {
        Account {
            account_id,
            tenant_id,
            username,
            password,
            realname,
            user_type,
            phone,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserType {
    #[serde(rename = "USER")]
    USER,
    #[serde(rename = "ADMIN")]
    ADMIN,
    #[serde(rename = "SUPERADMIN")]
    SUPERADMIN,
}

impl Default for UserType {
    fn default() -> UserType {
        Self::USER
    }
}

