/*
 * User and Authentication Backend
 *
 * # API for authentication and managing user accounts  This is the API of the service at P7M that manages tenants, accounts and authentication. It is the basis of many services of P7M.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.13.0
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "tenantId")]
    pub tenant_id: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "realname")]
    pub realname: String,
    #[serde(rename = "userType")]
    pub user_type: crate::models::UserType,
    #[serde(rename = "phone")]
    pub phone: String,
}

impl Account {
    pub fn new(account_id: String, tenant_id: String, username: String, password: String, realname: String, user_type: crate::models::UserType, phone: String) -> Account {
        Account {
            account_id,
            tenant_id,
            username,
            password,
            realname,
            user_type,
            phone,
        }
    }
}


