/*
 * User and Authentication Backend
 *
 * # API for authentication and managing user accounts  This is the API of the service at P7M that manages tenants, accounts and authentication. It is the basis of many services of P7M.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.14.2
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListWrapperAccountDataInner : An account that can be used to authenticate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWrapperAccountDataInner {
    /// ID of the account
    #[serde(rename = "accountId")]
    pub account_id: uuid::Uuid,
    /// Tenant this account belongs to
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    /// Username of the account
    #[serde(rename = "username")]
    pub username: String,
    /// Real name of the account holder
    #[serde(rename = "realname")]
    pub realname: String,
    /// Type of the account
    #[serde(rename = "userType")]
    pub user_type: models::UserType,
    /// Phone number of the account holder
    #[serde(rename = "phone")]
    pub phone: String,
    /// Last change of the account
    #[serde(rename = "lastChange")]
    pub last_change: String,
}

impl ListWrapperAccountDataInner {
    /// An account that can be used to authenticate
    pub fn new(account_id: uuid::Uuid, tenant_id: uuid::Uuid, username: String, realname: String, user_type: models::UserType, phone: String, last_change: String) -> ListWrapperAccountDataInner {
        ListWrapperAccountDataInner {
            account_id,
            tenant_id,
            username,
            realname,
            user_type,
            phone,
            last_change,
        }
    }
}

