/*
 * User and Authentication Backend
 *
 * # API for authentication and managing user accounts  This is the API of the service at P7M that manages tenants, accounts and authentication. It is the basis of many services of P7M.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.14.2
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NewAccount : Data for a new account or to change an existing account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewAccount {
    /// Username of the account
    #[serde(rename = "username")]
    pub username: String,
    /// Password of the account (on update an empty password means no change)
    #[serde(rename = "password")]
    pub password: String,
    /// Real name of the account holder
    #[serde(rename = "realname")]
    pub realname: String,
    /// Type of the account
    #[serde(rename = "userType")]
    pub user_type: models::UserType,
    /// Phone number of the account holder
    #[serde(rename = "phone")]
    pub phone: String,
}

impl NewAccount {
    /// Data for a new account or to change an existing account
    pub fn new(username: String, password: String, realname: String, user_type: models::UserType, phone: String) -> NewAccount {
        NewAccount {
            username,
            password,
            realname,
            user_type,
            phone,
        }
    }
}

