/*
 * User and Authentication Backend
 *
 * # API for authentication and managing user accounts  This is the API of the service at P7M that manages tenants, accounts and authentication. It is the basis of many services of P7M.  The caller has to be authenticated with the system and provide a JWT token in the Authorization header of the HTTP request. When using the API you typically get this token by authenticating first with OAuth 2.0.  When you are trying this API using the Swagger interface, you need to click the `Authorize` button and then again the Authorize button in the pop-up that gets opened.
 *
 * The version of the OpenAPI document: 0.14.2
 * Contact: tech@p7m.de
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordLoginResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "jwt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub jwt: Option<Option<String>>,
    #[serde(rename = "accountId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "realname", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub realname: Option<Option<String>>,
    #[serde(rename = "tenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "userType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_type: Option<Option<models::UserType>>,
    #[serde(rename = "expiration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiration: Option<Option<String>>,
    #[serde(rename = "accessibleTenants")]
    pub accessible_tenants: Vec<models::Tenant>,
}

impl PasswordLoginResponse {
    pub fn new(success: bool, accessible_tenants: Vec<models::Tenant>) -> PasswordLoginResponse {
        PasswordLoginResponse {
            success,
            jwt: None,
            account_id: None,
            realname: None,
            tenant_id: None,
            user_type: None,
            expiration: None,
            accessible_tenants,
        }
    }
}

